### PR TITLE
setup atlantis

### PR DESCRIPTION
**Pull request by faultables**

### CODE REVIEW

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform init -input=false" in "/home/faultable/.atlantis/repos/evilfactorylabs/area13/1/default": exit status 1

Initializing Terraform Cloud...
╷
│ Error: Required token could not be found
│ 
│ Run the following command to generate a token for app.terraform.io:
│     terraform login
╵


```

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform workspace new default" in "/home/faultable/.atlantis/repos/evilfactorylabs/area13/1/default": exit status 1: default workspace not supported
You can create a new workspace with the "workspace new" command.


```

**Comment by faultables** [comment]
goblok

**Comment by faultables** [comment]
atlantis plan -w area13

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform init -input=false" in "/home/faultable/.atlantis/repos/evilfactorylabs/area13/1/area13": exit status 1

Initializing Terraform Cloud...

Initializing provider plugins...
- Reusing previous version of digitalocean/digitalocean from the dependency lock file
- Reusing previous version of namecheap/namecheap from the dependency lock file
- Using digitalocean/digitalocean v2.21.0 from the shared cache directory
- Using namecheap/namecheap v2.1.0 from the shared cache directory
╷
│ Error: Failed to install provider from shared cache
│ 
│ Error while importing digitalocean/digitalocean v2.21.0 from the shared
│ cache directory: the provider cache at .terraform/providers has a copy of
│ registry.terraform.io/digitalocean/digitalocean 2.21.0 that doesn't match
│ any of the checksums recorded in the dependency lock file.
╵

╷
│ Error: Failed to install provider from shared cache
│ 
│ Error while importing namecheap/namecheap v2.1.0 from the shared cache
│ directory: the provider cache at .terraform/providers has a copy of
│ registry.terraform.io/namecheap/namecheap 2.1.0 that doesn't match any of
│ the checksums recorded in the dependency lock file.
╵


```
</details>

**Comment by anakmagang** [comment]
**Plan Error**
```
looking for atlantis.yaml file in "/home/faultable/.atlantis/repos/evilfactorylabs/area13/1/default": found "atlantis.yml" as config file; rename using the .yaml extension - "atlantis.yaml"
```

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/faultable/.atlantis/repos/evilfactorylabs/area13/1/area13/area13.tfplan\"" in "/home/faultable/.atlantis/repos/evilfactorylabs/area13/1/area13": exit status 1
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 1:
│    1: variable "do_token" {
│ 
│ The root module input variable "do_token" is not set, and has no default
│ value. Use a -var or -var-file command line argument to provide a value for
│ this variable.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 9:
│    9: variable "namecheap_username" {
│ 
│ The root module input variable "namecheap_username" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 13:
│   13: variable "namecheap_api_user" {
│ 
│ The root module input variable "namecheap_api_user" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 17:
│   17: variable "namecheap_api_key" {
│ 
│ The root module input variable "namecheap_api_key" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵

```
</details>

**Comment by anakmagang** [comment]
**Plan Error**
```
parsing atlantis.yaml: yaml: line 13: mapping values are not allowed in this context
```

**Comment by anakmagang** [comment]
**Plan Error**
```
parsing atlantis.yaml: yaml: line 13: mapping values are not allowed in this context
```

**Comment by anakmagang** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by faultables** [comment]
yowwwwww atlantis plan

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by faultables** [comment]
PLANNNNNN

**Comment by faultables** [comment]
coba plan

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

```diff

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.org/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by anakmagang** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `area13`

**Comment by anakmagang** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Atlantis commands can't be run on closed pull requests

**Pull request merged**
