### PR TITLE
test-openresty-traefik-wano-close-soon

### PR DESCRIPTION
**Pull request by faultables**

### CODE REVIEW

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false" in "/home/atlantis/.atlantis/repos/evilfactorylabs/area13/15/area13": exit status 1

Initializing Terraform Cloud...
╷
│ Error: Failed to request discovery document: 503 Service Unavailable
│ 
│   on main.tf line 13, in terraform:
│   13:   cloud {
│ 
╵


```

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false" in "/home/atlantis/.atlantis/repos/evilfactorylabs/area13/15/area13": exit status 1

Initializing Terraform Cloud...
╷
│ Error: Failed to request discovery document: 503 Service Unavailable
│ 
│   on main.tf line 13, in terraform:
│   13:   cloud {
│ 
╵


```

**Comment by faultables** [comment]
nvm SLA 900%

CleanShot 2023-11-05 at 23 40 18

CleanShot 2023-11-05 at 23 40 52

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -out \"/home/atlantis/.atlantis/repos/evilfactorylabs/area13/15/area13/area13.tfplan\" -var-file /home/atlantis/area13.tfvars" in "/home/atlantis/.atlantis/repos/evilfactorylabs/area13/15/area13": exit status 1
Acquiring state lock. This may take a few moments...
digitalocean_droplet.forem: Refreshing state... [id=255862486]
digitalocean_domain.evlfctrypro: Refreshing state... [id=evlfctry.pro]
digitalocean_spaces_bucket.evilfactorylabs-social: Refreshing state... [id=evilfactorylabs-social]
digitalocean_vpc.default_sgp: Refreshing state... [id=8e9d1d94-ca3d-4b0a-a489-f0ffec8e3a2b]
digitalocean_domain.evilfactorylabs_social: Refreshing state... [id=evilfactorylabs.social]
digitalocean_droplet.evilfactorylabs_social: Refreshing state... [id=362825530]
namecheap_domain_records.evlfctry-pro: Refreshing state... [id=evlfctry.pro]
digitalocean_record.evlfctrypro_apex["185.199.110.153"]: Refreshing state... [id=328768465]
digitalocean_record.evlfctrypro_apex["185.199.109.153"]: Refreshing state... [id=328768462]
digitalocean_record.evlfctrypro_www: Refreshing state... [id=328768463]
digitalocean_record.evlfctrypro_github_domain_verification: Refreshing state... [id=328768461]
digitalocean_record.evlfctrypro_apex["185.199.111.153"]: Refreshing state... [id=328768464]
digitalocean_record.evlfctrypro_apex["185.199.108.153"]: Refreshing state... [id=328768460]
digitalocean_firewall.forem: Refreshing state... [id=cdaa6351-3e24-481d-984a-d58383c13f2a]
digitalocean_domain.evilfactorylabs: Refreshing state... [id=evilfactorylabs.org]
digitalocean_record.evilfactorylabs_social_mailgun_dkim: Refreshing state... [id=1701135762]
digitalocean_record.evilfactorylabs_social_cdn: Refreshing state... [id=1701135773]
digitalocean_record.evilfactorylabs_social_mailgun_mx["0"]: Refreshing state... [id=1701135761]
digitalocean_record.evilfactorylabs_social_mailgun: Refreshing state... [id=1701135772]
digitalocean_record.evilfactorylabs_social_mailgun_spf: Refreshing state... [id=1701135760]
digitalocean_record.evilfactorylabs_social_mailgun_mx["1"]: Refreshing state... [id=1701135775]
namecheap_domain_records.evilfactorylabs-social: Refreshing state... [id=evilfactorylabs.social]
digitalocean_record.evilfactorylabs_social_u: Refreshing state... [id=1701135771]
digitalocean_record.evilfactorylabs_social_apex: Refreshing state... [id=1701135774]
digitalocean_record.evilfactorylabs_ns["ns2.digitalocean.com"]: Refreshing state... [id=328765841]
namecheap_domain_records.evilfactorylabs-org: Refreshing state... [id=evilfactorylabs.org]
digitalocean_record.evilfactorylabs_mailgun_mx["0"]: Refreshing state... [id=328757544]
digitalocean_record.evilfactorylabs_ns["ns3.digitalocean.com"]: Refreshing state... [id=328765843]
digitalocean_record.evilfactorylabs_ns["ns1.digitalocean.com"]: Refreshing state... [id=328765844]
digitalocean_record.evilfactorylabs_mailgun_mx["1"]: Refreshing state... [id=328757546]
digitalocean_record.evilfactorylabs_mailgun_cname: Refreshing state... [id=328757543]
digitalocean_record.evilfactorylabs_handbook: Refreshing state... [id=328757538]
digitalocean_record.evilfactorylabs_github_domain_verification: Refreshing state... [id=328757487]
digitalocean_record.evilfactorylabs_mailgun_dkim: Refreshing state... [id=328757484]
digitalocean_record.evilfactorylabs_about: Refreshing state... [id=328757539]
digitalocean_record.evilfactorylabs_www: Refreshing state... [id=328757488]
digitalocean_record.evilfactorylabs_migadu_mx["0"]: Refreshing state... [id=328757552]
digitalocean_record.evilfactorylabs_resources: Refreshing state... [id=328757542]
digitalocean_record.evilfactorylabs_migadu_spf: Refreshing state... [id=328757483]
digitalocean_record.evilfactorylabs_migadu_dkim: Refreshing state... [id=328757489]
digitalocean_record.evilfactorylabs_migadu_mx["1"]: Refreshing state... [id=328757548]
digitalocean_record.evilfactorylabs_dmarc: Refreshing state... [id=328757482]
digitalocean_record.evilfactorylabs_localhost: Refreshing state... [id=328787290]
digitalocean_record.evilfactorylabs_migadu_cname["key1"]: Refreshing state... [id=328757550]
digitalocean_record.evilfactorylabs_mailgun_spf: Refreshing state... [id=328757486]
digitalocean_record.evilfactorylabs_migadu_cname["key2"]: Refreshing state... [id=328757549]
digitalocean_record.evilfactorylabs_migadu_cname["key3"]: Refreshing state... [id=328757540]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform planned the following actions, but then encountered a problem:

  # digitalocean_record.evilfactorylabs_localhost will be updated in-place
  ~ resource "digitalocean_record" "evilfactorylabs_localhost" {
        id       = "328787290"
        name     = "localhost"
      ~ value    = "127.0.0.1" -> "127.0.0.11"
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "linode_token" but a
│ value was found in file "/home/atlantis/area13.tfvars". If you meant to use
│ this value, add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
╷
│ Error: Invalid request IP: 114.124.215.152 (1011150)
│ 
│   with namecheap_domain_records.evilfactorylabs-org,
│   on namecheap_dns.tf line 1, in resource "namecheap_domain_records" "evilfactorylabs-org":
│    1: resource "namecheap_domain_records" "evilfactorylabs-org" {
│ 
╵
╷
│ Error: Invalid request IP: 114.124.215.152 (1011150)
│ 
│   with namecheap_domain_records.evilfactorylabs-social,
│   on namecheap_dns.tf line 8, in resource "namecheap_domain_records" "evilfactorylabs-social":
│    8: resource "namecheap_domain_records" "evilfactorylabs-social" {
│ 
╵
╷
│ Error: Invalid request IP: 114.124.215.152 (1011150)
│ 
│   with namecheap_domain_records.evlfctry-pro,
│   on namecheap_dns.tf line 15, in resource "namecheap_domain_records" "evlfctry-pro":
│   15: resource "namecheap_domain_records" "evlfctry-pro" {
│ 
╵
Releasing state lock. This may take a few moments...

```
</details>

**Comment by faultables** [comment]
fak ada ip jaringan rumah gw wkwkwkkwkw

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -out \"/home/atlantis/.atlantis/repos/evilfactorylabs/area13/15/area13/area13.tfplan\" -var-file /home/atlantis/area13.tfvars" in "/home/atlantis/.atlantis/repos/evilfactorylabs/area13/15/area13": exit status 1
Acquiring state lock. This may take a few moments...
digitalocean_domain.evilfactorylabs_social: Refreshing state... [id=evilfactorylabs.social]
digitalocean_droplet.forem: Refreshing state... [id=255862486]
digitalocean_domain.evlfctrypro: Refreshing state... [id=evlfctry.pro]
digitalocean_spaces_bucket.evilfactorylabs-social: Refreshing state... [id=evilfactorylabs-social]
digitalocean_vpc.default_sgp: Refreshing state... [id=8e9d1d94-ca3d-4b0a-a489-f0ffec8e3a2b]
digitalocean_droplet.evilfactorylabs_social: Refreshing state... [id=362825530]
digitalocean_record.evlfctrypro_www: Refreshing state... [id=328768463]
digitalocean_record.evlfctrypro_github_domain_verification: Refreshing state... [id=328768461]
digitalocean_record.evlfctrypro_apex["185.199.109.153"]: Refreshing state... [id=328768462]
namecheap_domain_records.evlfctry-pro: Refreshing state... [id=evlfctry.pro]
digitalocean_record.evlfctrypro_apex["185.199.111.153"]: Refreshing state... [id=328768464]
digitalocean_record.evlfctrypro_apex["185.199.110.153"]: Refreshing state... [id=328768465]
digitalocean_record.evlfctrypro_apex["185.199.108.153"]: Refreshing state... [id=328768460]
namecheap_domain_records.evilfactorylabs-social: Refreshing state... [id=evilfactorylabs.social]
digitalocean_record.evilfactorylabs_social_mailgun_dkim: Refreshing state... [id=1701135762]
digitalocean_record.evilfactorylabs_social_mailgun_spf: Refreshing state... [id=1701135760]
digitalocean_record.evilfactorylabs_social_mailgun_mx["0"]: Refreshing state... [id=1701135761]
digitalocean_record.evilfactorylabs_social_cdn: Refreshing state... [id=1701135773]
digitalocean_record.evilfactorylabs_social_mailgun_mx["1"]: Refreshing state... [id=1701135775]
digitalocean_domain.evilfactorylabs: Refreshing state... [id=evilfactorylabs.org]
digitalocean_record.evilfactorylabs_social_mailgun: Refreshing state... [id=1701135772]
digitalocean_record.evilfactorylabs_social_apex: Refreshing state... [id=1701135774]
digitalocean_record.evilfactorylabs_social_u: Refreshing state... [id=1701135771]
digitalocean_record.evilfactorylabs_ns["ns1.digitalocean.com"]: Refreshing state... [id=328765844]
digitalocean_firewall.forem: Refreshing state... [id=cdaa6351-3e24-481d-984a-d58383c13f2a]
digitalocean_record.evilfactorylabs_ns["ns2.digitalocean.com"]: Refreshing state... [id=328765841]
digitalocean_record.evilfactorylabs_mailgun_cname: Refreshing state... [id=328757543]
digitalocean_record.evilfactorylabs_ns["ns3.digitalocean.com"]: Refreshing state... [id=328765843]
digitalocean_record.evilfactorylabs_mailgun_dkim: Refreshing state... [id=328757484]
digitalocean_record.evilfactorylabs_handbook: Refreshing state... [id=328757538]
digitalocean_record.evilfactorylabs_www: Refreshing state... [id=328757488]
digitalocean_record.evilfactorylabs_migadu_mx["0"]: Refreshing state... [id=328757552]
namecheap_domain_records.evilfactorylabs-org: Refreshing state... [id=evilfactorylabs.org]
digitalocean_record.evilfactorylabs_dmarc: Refreshing state... [id=328757482]
digitalocean_record.evilfactorylabs_migadu_mx["1"]: Refreshing state... [id=328757548]
digitalocean_record.evilfactorylabs_migadu_spf: Refreshing state... [id=328757483]
digitalocean_record.evilfactorylabs_resources: Refreshing state... [id=328757542]
digitalocean_record.evilfactorylabs_migadu_dkim: Refreshing state... [id=328757489]
digitalocean_record.evilfactorylabs_about: Refreshing state... [id=328757539]
digitalocean_record.evilfactorylabs_localhost: Refreshing state... [id=328787290]
digitalocean_record.evilfactorylabs_mailgun_spf: Refreshing state... [id=328757486]
digitalocean_record.evilfactorylabs_migadu_cname["key3"]: Refreshing state... [id=328757540]
digitalocean_record.evilfactorylabs_migadu_cname["key2"]: Refreshing state... [id=328757549]
digitalocean_record.evilfactorylabs_migadu_cname["key1"]: Refreshing state... [id=328757550]
digitalocean_record.evilfactorylabs_github_domain_verification: Refreshing state... [id=328757487]
digitalocean_record.evilfactorylabs_mailgun_mx["0"]: Refreshing state... [id=328757544]
digitalocean_record.evilfactorylabs_mailgun_mx["1"]: Refreshing state... [id=328757546]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform planned the following actions, but then encountered a problem:

  # digitalocean_record.evilfactorylabs_localhost will be updated in-place
  ~ resource "digitalocean_record" "evilfactorylabs_localhost" {
        id       = "328787290"
        name     = "localhost"
      ~ value    = "127.0.0.1" -> "127.0.0.11"
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "linode_token" but a
│ value was found in file "/home/atlantis/area13.tfvars". If you meant to use
│ this value, add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
╷
│ Error: Invalid request IP: 172.232.237.63 (1011150)
│ 
│   with namecheap_domain_records.evilfactorylabs-org,
│   on namecheap_dns.tf line 1, in resource "namecheap_domain_records" "evilfactorylabs-org":
│    1: resource "namecheap_domain_records" "evilfactorylabs-org" {
│ 
╵
╷
│ Error: Invalid request IP: 172.232.237.63 (1011150)
│ 
│   with namecheap_domain_records.evilfactorylabs-social,
│   on namecheap_dns.tf line 8, in resource "namecheap_domain_records" "evilfactorylabs-social":
│    8: resource "namecheap_domain_records" "evilfactorylabs-social" {
│ 
╵
╷
│ Error: Invalid request IP: 172.232.237.63 (1011150)
│ 
│   with namecheap_domain_records.evlfctry-pro,
│   on namecheap_dns.tf line 15, in resource "namecheap_domain_records" "evlfctry-pro":
│   15: resource "namecheap_domain_records" "evlfctry-pro" {
│ 
╵
Releasing state lock. This may take a few moments...

```
</details>

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # digitalocean_record.evilfactorylabs_localhost will be updated in-place
~ resource "digitalocean_record" "evilfactorylabs_localhost" {
        id       = "328787290"
        name     = "localhost"
      ~ value    = "127.0.0.1" -> "127.0.0.11"
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "linode_token" but a
│ value was found in file "/home/atlantis/area13.tfvars". If you meant to use
│ this value, add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.cloud/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`
</details>
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by faultables** [comment]
atlantis unlock

**Comment by anakmagang** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `area13`

**Comment by anakmagang** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Pull request closed without merging**
