### PR TITLE
Move atlantis to homeserver

### PR DESCRIPTION
**Pull request by faultables**

### CODE REVIEW

**Comment by faultables** [comment]
atlantis plan

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for 0 projects:

**Comment by faultables** [comment]
atlantis state list

**Comment by anakmagang** [comment]
```
Error: unknown command "state".
Run 'atlantis --help' for usage.
Available commands(--allow-commands): version, plan, apply, unlock, approve_policies
```

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for 0 projects:

**Comment by anakmagang** [comment]
**Error: goroutine panic. This is a bug.**
```
page 4 already freed
go.etcd.io/bbolt@v1.3.7/freelist.go:175 (0xb276d3)
go.etcd.io/bbolt@v1.3.7/node.go:363 (0xb2b4a5)
go.etcd.io/bbolt@v1.3.7/bucket.go:584 (0xb20029)
go.etcd.io/bbolt@v1.3.7/bucket.go:551 (0xb1fe06)
go.etcd.io/bbolt@v1.3.7/tx.go:163 (0xb2dff8)
go.etcd.io/bbolt@v1.3.7/db.go:869 (0xb24e11)
github.com/runatlantis/atlantis/server/core/db/boltdb.go:323 (0xb35b29)
github.com/runatlantis/atlantis/server/events/db_updater.go:26 (0xf65597)
github.com/runatlantis/atlantis/server/events/plan_command_runner.go:270 (0xf761c5)
github.com/runatlantis/atlantis/server/events/plan_command_runner.go:292 (0xf76764)
github.com/runatlantis/atlantis/server/events/command_runner.go:301 (0xf5bbc7)
runtime/asm_amd64.s:1650 (0x46ca80)
```

**Comment by faultables** [comment]
> **Error: goroutine panic. This is a bug.**
> 
> ```
> page 4 already freed
> go.etcd.io/bbolt@v1.3.7/freelist.go:175 (0xb276d3)
> go.etcd.io/bbolt@v1.3.7/node.go:363 (0xb2b4a5)
> go.etcd.io/bbolt@v1.3.7/bucket.go:584 (0xb20029)
> go.etcd.io/bbolt@v1.3.7/bucket.go:551 (0xb1fe06)
> go.etcd.io/bbolt@v1.3.7/tx.go:163 (0xb2dff8)
> go.etcd.io/bbolt@v1.3.7/db.go:869 (0xb24e11)
> github.com/runatlantis/atlantis/server/core/db/boltdb.go:323 (0xb35b29)
> github.com/runatlantis/atlantis/server/events/db_updater.go:26 (0xf65597)
> github.com/runatlantis/atlantis/server/events/plan_command_runner.go:270 (0xf761c5)
> github.com/runatlantis/atlantis/server/events/plan_command_runner.go:292 (0xf76764)
> github.com/runatlantis/atlantis/server/events/command_runner.go:301 (0xf5bbc7)
> runtime/asm_amd64.s:1650 (0x46ca80)
> ```

nice

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for 0 projects:

**Comment by faultables** [comment]
bismillah terraform apply

**Comment by faultables** [comment]
terraform plan

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Did you mean to use `atlantis` instead of `terraform`?

**Comment by anakmagang** [comment]
**Plan Error**
```
running git clone --depth=1 --branch move-to-homeserver --single-branch https://anakmagang:<redacted>@github.com/evilfactorylabs/area13.git /home/atlantis/.atlantis/repos/evilfactorylabs/area13/13/default: Cloning into '/home/atlantis/.atlantis/repos/evilfactorylabs/area13/13/default'...
fatal: unable to access 'https://github.com/evilfactorylabs/area13.git/': Could not resolve host: github.com
: exit status 128
```

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # digitalocean_firewall.forem will be updated in-place
~ resource "digitalocean_firewall" "forem" {
        id              = "cdaa6351-3e24-481d-984a-d58383c13f2a"
        name            = "www.evilfactorylabs.org"
        tags            = []
        # (4 unchanged attributes hidden)

      - inbound_rule {
          - port_range                = "22" -> null
          - protocol                  = "tcp" -> null
          - source_addresses          = [
              - "100.64.0.0/10",
            ] -> null
          - source_droplet_ids        = [] -> null
          - source_kubernetes_ids     = [] -> null
          - source_load_balancer_uids = [] -> null
          - source_tags               = [] -> null
        }
      + inbound_rule {
          + port_range                = "22"
          + protocol                  = "tcp"
          + source_addresses          = [
              + "0.0.0.0/0",
            ]
          + source_droplet_ids        = []
          + source_kubernetes_ids     = []
          + source_load_balancer_uids = []
          + source_tags               = []
        }

        # (6 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "linode_token" but a
│ value was found in file "/home/atlantis/area13.tfvars". If you meant to use
│ this value, add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.cloud/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`
</details>
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for 0 projects:

**Comment by faultables** [comment]
atlantis unlock

**Comment by anakmagang** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Pull request merged**
