### PR TITLE
change atlantis.evilfactorylabs.org

### PR DESCRIPTION
**Pull request by faultables**

### CODE REVIEW

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # digitalocean_record.evilfactorylabs_atlantis must be replaced
-/+ resource "digitalocean_record" "evilfactorylabs_atlantis" {
      - flags    = 0 -> null
      ~ fqdn     = "atlantis.evilfactorylabs.org" -> (known after apply)
      ~ id       = "328776208" -> (known after apply)
        name     = "atlantis"
      - port     = 0 -> null
      - priority = 0 -> null
      ~ ttl      = 1800 -> (known after apply)
      ~ type     = "A" -> "CNAME" # forces replacement
      ~ value    = "103.179.56.192" -> "cname.edgy.network"
      - weight   = 0 -> null
        # (1 unchanged attribute hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.org/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`
</details>
Plan: 1 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by faultables** [comment]
atlantis apply

**Comment by anakmagang** [comment]
Ran Apply for dir: `.` workspace: `area13`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform apply -input=false \"/root/.atlantis/repos/evilfactorylabs/area13/3/area13/area13.tfplan\"" in "/root/.atlantis/repos/evilfactorylabs/area13/3/area13": exit status 1
Acquiring state lock. This may take a few moments...
digitalocean_record.evilfactorylabs_atlantis: Destroying... [id=328776208]
digitalocean_record.evilfactorylabs_atlantis: Destruction complete after 1s
digitalocean_record.evilfactorylabs_atlantis: Creating...
╷
│ Error: Failed to create record: POST https://api.digitalocean.com/v2/domains/evilfactorylabs.org/records: 422 (request "564b524d-d192-4c2e-bb6e-cf5446ef7450") Data needs to end with a dot (.)
│ 
│   with digitalocean_record.evilfactorylabs_atlantis,
│   on do_dns.tf line 57, in resource "digitalocean_record" "evilfactorylabs_atlantis":
│   57: resource "digitalocean_record" "evilfactorylabs_atlantis" {
│ 
╵

```
</details>

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # digitalocean_record.evilfactorylabs_atlantis will be created
+ resource "digitalocean_record" "evilfactorylabs_atlantis" {
      + domain = "evilfactorylabs.org"
      + fqdn   = (known after apply)
      + id     = (known after apply)
      + name   = "atlantis"
      + ttl    = (known after apply)
      + type   = "CNAME"
      + value  = "cname.edgy.network."
    }

Plan: 1 to add, 0 to change, 0 to destroy.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.org/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by faultables** [comment]
atlantis apply

**Comment by faultables** [comment]
atlantis apply -w area13

**Comment by anakmagang** [comment]
Ran Apply for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff
Acquiring state lock. This may take a few moments...
digitalocean_record.evilfactorylabs_atlantis: Creating...
digitalocean_record.evilfactorylabs_atlantis: Creation complete after 2s [id=334997101]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

evilfactorylabs_forem_image_id = "88327586"
evilfactorylabs_forem_ip = "174.138.16.134"
evilfactorylabs_forem_region = "sgp1"
evilfactorylabs_forem_vpc = "8e9d1d94-ca3d-4b0a-a489-f0ffec8e3a2b"

```
</details>

**Comment by anakmagang** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `area13`

**Pull request merged**
