### PR TITLE
remove fm

### PR DESCRIPTION
**Pull request by faultables**

### CODE REVIEW

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
- destroy

Terraform will perform the following actions:

  # digitalocean_firewall.forem will be updated in-place
~ resource "digitalocean_firewall" "forem" {
        id              = "cdaa6351-3e24-481d-984a-d58383c13f2a"
        name            = "www.evilfactorylabs.org"
        tags            = []
        # (4 unchanged attributes hidden)

      - inbound_rule {
          - port_range                = "22" -> null
          - protocol                  = "tcp" -> null
          - source_addresses          = [
              - "100.64.0.0/10",
              - "103.213.129.0/24",
            ] -> null
          - source_droplet_ids        = [] -> null
          - source_kubernetes_ids     = [] -> null
          - source_load_balancer_uids = [] -> null
          - source_tags               = [] -> null
        }
      + inbound_rule {
          + port_range                = "22"
          + protocol                  = "tcp"
          + source_addresses          = [
              + "100.64.0.0/10",
            ]
          + source_droplet_ids        = []
          + source_kubernetes_ids     = []
          + source_load_balancer_uids = []
          + source_tags               = []
        }

      + outbound_rule {
          + destination_addresses          = [
              + "0.0.0.0/0",
            ]
          + destination_droplet_ids        = []
          + destination_kubernetes_ids     = []
          + destination_load_balancer_uids = []
          + destination_tags               = []
          + port_range                     = "1-65535"
          + protocol                       = "tcp"
        }
      + outbound_rule {
          + destination_addresses          = [
              + "0.0.0.0/0",
            ]
          + destination_droplet_ids        = []
          + destination_kubernetes_ids     = []
          + destination_load_balancer_uids = []
          + destination_tags               = []
          + port_range                     = "1-65535"
          + protocol                       = "udp"
        }
      - outbound_rule {
          - destination_addresses          = [
              - "0.0.0.0/0",
            ] -> null
          - destination_droplet_ids        = [] -> null
          - destination_kubernetes_ids     = [] -> null
          - destination_load_balancer_uids = [] -> null
          - destination_tags               = [] -> null
          - port_range                     = "all" -> null
          - protocol                       = "tcp" -> null
        }
      - outbound_rule {
          - destination_addresses          = [
              - "0.0.0.0/0",
            ] -> null
          - destination_droplet_ids        = [] -> null
          - destination_kubernetes_ids     = [] -> null
          - destination_load_balancer_uids = [] -> null
          - destination_tags               = [] -> null
          - port_range                     = "all" -> null
          - protocol                       = "udp" -> null
        }

        # (4 unchanged blocks hidden)
    }

  # digitalocean_record.evilfactorylabs_fm will be destroyed
  # (because digitalocean_record.evilfactorylabs_fm is not in configuration)
- resource "digitalocean_record" "evilfactorylabs_fm" {
      - domain   = "evilfactorylabs.org" -> null
      - flags    = 0 -> null
      - fqdn     = "fm.evilfactorylabs.org" -> null
      - id       = "338348506" -> null
      - name     = "fm" -> null
      - port     = 0 -> null
      - priority = 0 -> null
      - ttl      = 1800 -> null
      - type     = "A" -> null
      - value    = "103.3.62.193" -> null
      - weight   = 0 -> null
    }

Plan: 0 to add, 1 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.org/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`
</details>
Plan: 0 to add, 1 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by faultables** [comment]
atlantis apply

**Comment by anakmagang** [comment]
Ran Apply for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff
digitalocean_record.evilfactorylabs_fm: Destroying... [id=338348506]
digitalocean_firewall.forem: Modifying... [id=cdaa6351-3e24-481d-984a-d58383c13f2a]
digitalocean_record.evilfactorylabs_fm: Destruction complete after 1s
digitalocean_firewall.forem: Modifications complete after 2s [id=cdaa6351-3e24-481d-984a-d58383c13f2a]

Apply complete! Resources: 0 added, 1 changed, 1 destroyed.

Outputs:

evilfactorylabs_forem_image_id = "88327586"
evilfactorylabs_forem_ip = "174.138.16.134"
evilfactorylabs_forem_region = "sgp1"
evilfactorylabs_forem_vpc = "8e9d1d94-ca3d-4b0a-a489-f0ffec8e3a2b"

```
</details>

**Comment by anakmagang** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `area13`

**Pull request merged**
