### PR TITLE
Remove atlantis.evilfactorylabs.org

### PR DESCRIPTION
**Pull request by faultables**

### CODE REVIEW

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # digitalocean_record.evilfactorylabs_atlantis will be destroyed
  # (because digitalocean_record.evilfactorylabs_atlantis is not in configuration)
- resource "digitalocean_record" "evilfactorylabs_atlantis" {
      - domain   = "evilfactorylabs.org" -> null
      - flags    = 0 -> null
      - fqdn     = "atlantis.evilfactorylabs.org" -> null
      - id       = "334997101" -> null
      - name     = "atlantis" -> null
      - port     = 0 -> null
      - priority = 0 -> null
      - ttl      = 1800 -> null
      - type     = "CNAME" -> null
      - value    = "cname.edgy.network." -> null
      - weight   = 0 -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "linode_token" but a
│ value was found in file "/home/atlantis/area13.tfvars". If you meant to use
│ this value, add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.cloud/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`
</details>
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by faultables** [comment]
atlantis apply

**Comment by anakmagang** [comment]
Ran Apply for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff
Acquiring state lock. This may take a few moments...
digitalocean_record.evilfactorylabs_atlantis: Destroying... [id=334997101]
digitalocean_record.evilfactorylabs_atlantis: Destruction complete after 1s
Releasing state lock. This may take a few moments...

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.

Outputs:

evilfactorylabs_forem_image_id = "88327586"
evilfactorylabs_forem_ip = "174.138.16.134"
evilfactorylabs_forem_region = "sgp1"
evilfactorylabs_forem_vpc = "8e9d1d94-ca3d-4b0a-a489-f0ffec8e3a2b"
evilfactorylabs_social_ip = "178.128.103.137"
```

</details>

**Comment by anakmagang** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `area13`

**Pull request merged**
