### PR TITLE
Finalize evilfactorylabs.social

### PR DESCRIPTION
**Pull request by faultables**

### CODE REVIEW

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -out \"/etc/atlantis/.atlantis/repos/evilfactorylabs/area13/12/area13/area13.tfplan\" -var-file /etc/atlantis/area13.tfvars" in "/etc/atlantis/.atlantis/repos/evilfactorylabs/area13/12/area13": exit status 1
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "linode_token" but a
│ value was found in file "/etc/atlantis/area13.tfvars". If you meant to use
│ this value, add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
╷
│ Error: Value for unconfigurable attribute
│ 
│   with digitalocean_spaces_bucket.evilfactorylabs-social,
│   on do_spaces.tf line 2, in resource "digitalocean_spaces_bucket" "evilfactorylabs-social":
│    2:   bucket_domain_name = "evilfactorylabs-social.sgp1.digitaloceanspaces.com"
│ 
│ Can't configure a value for "bucket_domain_name": its value will be decided
│ automatically based on the result of applying this configuration.
╵
╷
│ Error: Invalid or unknown key
│ 
│   with digitalocean_spaces_bucket.evilfactorylabs-social,
│   on do_spaces.tf line 3, in resource "digitalocean_spaces_bucket" "evilfactorylabs-social":
│    3:   id                 = "evilfactorylabs-social"
│ 
╵
╷
│ Error: Value for unconfigurable attribute
│ 
│   with digitalocean_spaces_bucket.evilfactorylabs-social,
│   on do_spaces.tf line 6, in resource "digitalocean_spaces_bucket" "evilfactorylabs-social":
│    6:   urn                = "do:space:evilfactorylabs-social"
│ 
│ Can't configure a value for "urn": its value will be decided automatically
│ based on the result of applying this configuration.
╵

```
</details>

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place

Terraform will perform the following actions:

  # digitalocean_spaces_bucket.evilfactorylabs-social will be updated in-place
~ resource "digitalocean_spaces_bucket" "evilfactorylabs-social" {
      + acl                = "private"
      + force_destroy      = false
        id                 = "evilfactorylabs-social"
        name               = "evilfactorylabs-social"
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # namecheap_domain_records.evilfactorylabs-social will be created
+ resource "namecheap_domain_records" "evilfactorylabs-social" {
      + domain      = "evilfactorylabs.social"
      + id          = (known after apply)
      + mode        = "OVERWRITE"
      + nameservers = [
          + "ns1.digitalocean.com",
          + "ns2.digitalocean.com",
          + "ns3.digitalocean.com",
        ]
    }

Plan: 1 to add, 1 to change, 0 to destroy.
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "linode_token" but a
│ value was found in file "/etc/atlantis/area13.tfvars". If you meant to use
│ this value, add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.org/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`
</details>
Plan: 1 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by faultables** [comment]
atlantis apply

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
```
The area13 workspace at path . is currently locked by another command that is running for this pull request.
Wait until the previous command is complete and try again.
```

**Comment by anakmagang** [comment]
Ran Apply for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff
namecheap_domain_records.evilfactorylabs-social: Creating...
digitalocean_spaces_bucket.evilfactorylabs-social: Modifying... [id=evilfactorylabs-social]
digitalocean_spaces_bucket.evilfactorylabs-social: Modifications complete after 0s [id=evilfactorylabs-social]
namecheap_domain_records.evilfactorylabs-social: Creation complete after 2s [id=evilfactorylabs.social]

Apply complete! Resources: 1 added, 1 changed, 0 destroyed.

Outputs:

evilfactorylabs_forem_image_id = "88327586"
evilfactorylabs_forem_ip = "174.138.16.134"
evilfactorylabs_forem_region = "sgp1"
evilfactorylabs_forem_vpc = "8e9d1d94-ca3d-4b0a-a489-f0ffec8e3a2b"
evilfactorylabs_social_ip = "178.128.103.137"

```
</details>

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "linode_token" but a
│ value was found in file "/etc/atlantis/area13.tfvars". If you meant to use
│ this value, add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.org/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`
</details>
No changes. Your infrastructure matches the configuration.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by anakmagang** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `area13`

**Pull request merged**
