### PR TITLE
add localhost.evilfactorylabs.org

### PR DESCRIPTION
**Pull request by faultables**
demo purpose

### CODE REVIEW

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
```
running "/usr/bin/terraform init -input=false" in "/root/.atlantis/repos/evilfactorylabs/area13/2/area13": exit status 1

Initializing Terraform Cloud...
╷
│ Error: Required token could not be found
│ 
│ Run the following command to generate a token for app.terraform.io:
│     terraform login
╵


```

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # digitalocean_record.evilfactorylabs_localhost will be created
+ resource "digitalocean_record" "evilfactorylabs_localhost" {
      + domain = "evilfactorylabs.org"
      + fqdn   = (known after apply)
      + id     = (known after apply)
      + name   = "localhost"
      + ttl    = (known after apply)
      + type   = "A"
      + value  = "127.0.0.1"
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.org/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by faultables** [comment]
???

image

**Comment by faultables** [comment]
atlantis apply

**Comment by anakmagang** [comment]
Ran Apply for dir: `.` workspace: `area13`

```diff
digitalocean_record.evilfactorylabs_localhost: Creating...
digitalocean_record.evilfactorylabs_localhost: Creation complete after 1s [id=328787290]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

evilfactorylabs_forem_image_id = "88327586"
evilfactorylabs_forem_ip = "174.138.16.134"
evilfactorylabs_forem_region = "sgp1"
evilfactorylabs_forem_vpc = "8e9d1d94-ca3d-4b0a-a489-f0ffec8e3a2b"

```

**Comment by faultables** [comment]
nvm

**Comment by anakmagang** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `area13`

**Pull request merged**
