### PR TITLE
feat: add fm

### PR DESCRIPTION
**Pull request by faultables**

### CODE REVIEW

**Comment by faultables** [comment]
atlantis plan

**Comment by faultables** [comment]
atlantis plan

**Comment by faultables** [comment]
heloooo

**Comment by faultables** [comment]
atlantis apply

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
**Plan Error**
```
running git clone --branch dns/fm --depth=1 --single-branch https://anakmagang:<redacted>@github.com/evilfactorylabs/area13.git /root/.atlantis/repos/evilfactorylabs/area13/4/default: : exec: "git": executable file not found in $PATH
```

**Comment by faultables** [comment]
oalaa

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
```
running "/usr/bin/terraform init -input=false" in "/root/.atlantis/repos/evilfactorylabs/area13/4/area13": exit status 1

Initializing Terraform Cloud...
╷
│ Error: Required token could not be found
│ 
│ Run the following command to generate a token for app.terraform.io:
│     terraform login
╵


```

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
```
running "/usr/bin/terraform init -input=false" in "/root/.atlantis/repos/evilfactorylabs/area13/4/area13": exit status 1

Initializing Terraform Cloud...
╷
│ Error: Required token could not be found
│ 
│ Run the following command to generate a token for app.terraform.io:
│     terraform login
╵


```

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place

Terraform will perform the following actions:

  # digitalocean_firewall.forem will be updated in-place
~ resource "digitalocean_firewall" "forem" {
        id              = "cdaa6351-3e24-481d-984a-d58383c13f2a"
        name            = "www.evilfactorylabs.org"
        tags            = []
        # (4 unchanged attributes hidden)

      - inbound_rule {
          - port_range                = "22" -> null
          - protocol                  = "tcp" -> null
          - source_addresses          = [
              - "103.213.129.38",
            ] -> null
          - source_droplet_ids        = [] -> null
          - source_kubernetes_ids     = [] -> null
          - source_load_balancer_uids = [] -> null
          - source_tags               = [] -> null
        }

      + outbound_rule {
          + destination_addresses          = [
              + "0.0.0.0/0",
            ]
          + destination_droplet_ids        = []
          + destination_kubernetes_ids     = []
          + destination_load_balancer_uids = []
          + destination_tags               = []
          + port_range                     = "1-65535"
          + protocol                       = "tcp"
        }
      + outbound_rule {
          + destination_addresses          = [
              + "0.0.0.0/0",
            ]
          + destination_droplet_ids        = []
          + destination_kubernetes_ids     = []
          + destination_load_balancer_uids = []
          + destination_tags               = []
          + port_range                     = "1-65535"
          + protocol                       = "udp"
        }
      - outbound_rule {
          - destination_addresses          = [
              - "0.0.0.0/0",
            ] -> null
          - destination_droplet_ids        = [] -> null
          - destination_kubernetes_ids     = [] -> null
          - destination_load_balancer_uids = [] -> null
          - destination_tags               = [] -> null
          - port_range                     = "all" -> null
          - protocol                       = "tcp" -> null
        }
      - outbound_rule {
          - destination_addresses          = [
              - "0.0.0.0/0",
            ] -> null
          - destination_droplet_ids        = [] -> null
          - destination_kubernetes_ids     = [] -> null
          - destination_load_balancer_uids = [] -> null
          - destination_tags               = [] -> null
          - port_range                     = "all" -> null
          - protocol                       = "udp" -> null
        }

        # (5 unchanged blocks hidden)
    }

  # digitalocean_record.evilfactorylabs_fm will be created
+ resource "digitalocean_record" "evilfactorylabs_fm" {
      + domain = "evilfactorylabs.org"
      + fqdn   = (known after apply)
      + id     = (known after apply)
      + name   = "fm"
      + ttl    = (known after apply)
      + type   = "A"
      + value  = "103.3.62.193"
    }

Plan: 1 to add, 1 to change, 0 to destroy.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.org/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`
</details>
Plan: 1 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by faultables** [comment]
atlantis apply -w area13

**Comment by anakmagang** [comment]
Ran Apply for dir: `.` workspace: `area13`

<details><summary>Show Output</summary>

```diff
digitalocean_record.evilfactorylabs_fm: Creating...
digitalocean_firewall.forem: Modifying... [id=cdaa6351-3e24-481d-984a-d58383c13f2a]
digitalocean_record.evilfactorylabs_fm: Creation complete after 0s [id=338348506]
digitalocean_firewall.forem: Modifications complete after 1s [id=cdaa6351-3e24-481d-984a-d58383c13f2a]

Apply complete! Resources: 1 added, 1 changed, 0 destroyed.

Outputs:

evilfactorylabs_forem_image_id = "88327586"
evilfactorylabs_forem_ip = "174.138.16.134"
evilfactorylabs_forem_region = "sgp1"
evilfactorylabs_forem_vpc = "8e9d1d94-ca3d-4b0a-a489-f0ffec8e3a2b"

```
</details>

**Comment by anakmagang** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `area13`

**Pull request merged**
