### PR TITLE
add evilfactorylabs social

### PR DESCRIPTION
**Pull request by faultables**
lgtm

### CODE REVIEW

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/evilfactorylabs/area13/6/area13/area13.tfplan\" -var-file /etc/atlantis/area13.tfvars" in "/root/.atlantis/repos/evilfactorylabs/area13/6/area13": exit status 1
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 5:
│    5: variable "linode_token" {
│ 
│ The root module input variable "linode_token" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵

```

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform init -input=false" in "/root/.atlantis/repos/evilfactorylabs/area13/6/area13": exit status 1

Initializing Terraform Cloud...

Initializing provider plugins...
- Reusing previous version of linode/linode from the dependency lock file
- Reusing previous version of digitalocean/digitalocean from the dependency lock file
- Reusing previous version of namecheap/namecheap from the dependency lock file
- Using linode/linode v1.29.4 from the shared cache directory
- Using digitalocean/digitalocean v2.21.0 from the shared cache directory
- Using namecheap/namecheap v2.1.0 from the shared cache directory
╷
│ Error: Failed to install provider from shared cache
│ 
│ Error while importing linode/linode v1.29.4 from the shared cache
│ directory: the provider cache at .terraform/providers has a copy of
│ registry.terraform.io/linode/linode 1.29.4 that doesn't match any of the
│ checksums recorded in the dependency lock file.
╵


```
</details>

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/evilfactorylabs/area13/6/area13/area13.tfplan\" -var-file /etc/atlantis/area13.tfvars" in "/root/.atlantis/repos/evilfactorylabs/area13/6/area13": exit status 1
╷
│ Error: error getting default for "config_path": error loading default: $HOME is not defined
│ 
│   with provider["registry.terraform.io/linode/linode"],
│   on main.tf line 29, in provider "linode":
│   29: provider "linode" {
│ 
╵

```

**Comment by faultables** [comment]
the what

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

**Plan Error**
```
running "/usr/bin/terraform init -input=false" in "/etc/atlantis/.atlantis/repos/evilfactorylabs/area13/6/area13": exit status 1

Initializing Terraform Cloud...
╷
│ Error: Required token could not be found
│ 
│ Run the following command to generate a token for app.terraform.io:
│     terraform login
╵


```

**Comment by faultables** [comment]
atlantis plan

**Comment by anakmagang** [comment]
Ran Plan for dir: `.` workspace: `area13`

```diff

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w area13`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.evilfactorylabs.org/lock?id=evilfactorylabs%252Farea13%252F.%252Farea13)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w area13`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by faultables** [comment]
lgtm

**Comment by anakmagang** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `area13`

**Pull request merged**
